// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/contact" | "/cookie-policy" | "/corporate-account" | "/customers" | "/dashboard" | "/delivery-and-returns" | "/distance-sales-agreement" | "/faqs" | "/forgot-password" | "/login" | "/orders" | "/orders/[id]" | "/orders/[id]/payment" | "/orders/new" | "/pricing" | "/privacy-policy" | "/register" | "/reports" | "/reset-password" | "/services" | "/settings" | "/tr" | "/tr/ayarlar" | "/tr/cerez-politikasi" | "/tr/fiyatlandirma" | "/tr/giris" | "/tr/gizlilik-politikasi" | "/tr/hakkimizda" | "/tr/hizmetler" | "/tr/iletisim" | "/tr/kayit" | "/tr/mesafeli-satis-sozlesmesi" | "/tr/musteriler" | "/tr/panel" | "/tr/raporlar" | "/tr/sifre-sifirla" | "/tr/sifremi-unuttum" | "/tr/siparisler" | "/tr/siparisler/[id]" | "/tr/siparisler/[id]/payment" | "/tr/siparisler/new" | "/tr/sss" | "/tr/teslimat-ve-iade"
type AppRouteHandlerRoutes = "/api/admin/users/[id]/notes" | "/api/auth/[...nextauth]" | "/api/auth/forgot-password" | "/api/auth/logout-all" | "/api/auth/register" | "/api/auth/reset-password" | "/api/comments" | "/api/corporate-account" | "/api/cron/cleanup-orders" | "/api/files/[id]" | "/api/files/upload" | "/api/notifications" | "/api/orders" | "/api/orders/[id]" | "/api/orders/[id]/download-finals" | "/api/orders/[id]/wilcom" | "/api/orders/[id]/wilcom/image/[type]" | "/api/orders/[id]/wilcom/pdf/[type]" | "/api/orders/[id]/wilcom/publish" | "/api/user/avatar/upload" | "/api/user/delete-account" | "/api/user/delete-account/confirm" | "/api/user/password" | "/api/user/profile" | "/api/user/profile/verify"
type PageRoutes = never
type LayoutRoutes = "/" | "/tr"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/api/admin/users/[id]/notes": { "id": string; }
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/auth/forgot-password": {}
  "/api/auth/logout-all": {}
  "/api/auth/register": {}
  "/api/auth/reset-password": {}
  "/api/comments": {}
  "/api/corporate-account": {}
  "/api/cron/cleanup-orders": {}
  "/api/files/[id]": { "id": string; }
  "/api/files/upload": {}
  "/api/notifications": {}
  "/api/orders": {}
  "/api/orders/[id]": { "id": string; }
  "/api/orders/[id]/download-finals": { "id": string; }
  "/api/orders/[id]/wilcom": { "id": string; }
  "/api/orders/[id]/wilcom/image/[type]": { "id": string; "type": string; }
  "/api/orders/[id]/wilcom/pdf/[type]": { "id": string; "type": string; }
  "/api/orders/[id]/wilcom/publish": { "id": string; }
  "/api/user/avatar/upload": {}
  "/api/user/delete-account": {}
  "/api/user/delete-account/confirm": {}
  "/api/user/password": {}
  "/api/user/profile": {}
  "/api/user/profile/verify": {}
  "/contact": {}
  "/cookie-policy": {}
  "/corporate-account": {}
  "/customers": {}
  "/dashboard": {}
  "/delivery-and-returns": {}
  "/distance-sales-agreement": {}
  "/faqs": {}
  "/forgot-password": {}
  "/login": {}
  "/orders": {}
  "/orders/[id]": { "id": string; }
  "/orders/[id]/payment": { "id": string; }
  "/orders/new": {}
  "/pricing": {}
  "/privacy-policy": {}
  "/register": {}
  "/reports": {}
  "/reset-password": {}
  "/services": {}
  "/settings": {}
  "/tr": {}
  "/tr/ayarlar": {}
  "/tr/cerez-politikasi": {}
  "/tr/fiyatlandirma": {}
  "/tr/giris": {}
  "/tr/gizlilik-politikasi": {}
  "/tr/hakkimizda": {}
  "/tr/hizmetler": {}
  "/tr/iletisim": {}
  "/tr/kayit": {}
  "/tr/mesafeli-satis-sozlesmesi": {}
  "/tr/musteriler": {}
  "/tr/panel": {}
  "/tr/raporlar": {}
  "/tr/sifre-sifirla": {}
  "/tr/sifremi-unuttum": {}
  "/tr/siparisler": {}
  "/tr/siparisler/[id]": { "id": string; }
  "/tr/siparisler/[id]/payment": { "id": string; }
  "/tr/siparisler/new": {}
  "/tr/sss": {}
  "/tr/teslimat-ve-iade": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/tr": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
