module.exports = [
"[project]/Documents/nakis/src/app/favicon.ico.mjs { IMAGE => \"[project]/Documents/nakis/src/app/favicon.ico (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/Documents/nakis/src/app/favicon.ico.mjs { IMAGE => \"[project]/Documents/nakis/src/app/favicon.ico (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript)"));
}),
"[project]/Documents/nakis/src/app/icon.png.mjs { IMAGE => \"[project]/Documents/nakis/src/app/icon.png (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/Documents/nakis/src/app/icon.png.mjs { IMAGE => \"[project]/Documents/nakis/src/app/icon.png (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript)"));
}),
"[project]/Documents/nakis/src/app/apple-icon.png.mjs { IMAGE => \"[project]/Documents/nakis/src/app/apple-icon.png (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/Documents/nakis/src/app/apple-icon.png.mjs { IMAGE => \"[project]/Documents/nakis/src/app/apple-icon.png (static in ecmascript, tag client)\" } [app-rsc] (structured image object, ecmascript)"));
}),
"[externals]/next/dist/shared/lib/no-fallback-error.external.js [external] (next/dist/shared/lib/no-fallback-error.external.js, cjs)", ((__turbopack_context__, module, exports) => {

const mod = __turbopack_context__.x("next/dist/shared/lib/no-fallback-error.external.js", () => require("next/dist/shared/lib/no-fallback-error.external.js"));

module.exports = mod;
}),
"[project]/Documents/nakis/src/app/loading.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/Documents/nakis/src/app/loading.tsx [app-rsc] (ecmascript)"));
}),
"[project]/Documents/nakis/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/Documents/nakis/src/app/not-found.tsx [app-rsc] (ecmascript)"));
}),
"[project]/Documents/nakis/src/app/(en)/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/Documents/nakis/src/app/(en)/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/Documents/nakis/src/app/(en)/(dashboard)/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/Documents/nakis/src/app/(en)/(dashboard)/layout.tsx [app-rsc] (ecmascript)"));
}),
"[project]/Documents/nakis/src/app/(en)/(dashboard)/dashboard/dashboard-content.tsx [app-rsc] (client reference proxy) <module evaluation>", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "DashboardContent",
    ()=>DashboardContent
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Documents/nakis/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const DashboardContent = (0, __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call DashboardContent() from the server but DashboardContent is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/Documents/nakis/src/app/(en)/(dashboard)/dashboard/dashboard-content.tsx <module evaluation>", "DashboardContent");
}),
"[project]/Documents/nakis/src/app/(en)/(dashboard)/dashboard/dashboard-content.tsx [app-rsc] (client reference proxy)", ((__turbopack_context__) => {
"use strict";

// This file is generated by next-core EcmascriptClientReferenceModule.
__turbopack_context__.s([
    "DashboardContent",
    ()=>DashboardContent
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Documents/nakis/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-server-dom-turbopack-server.js [app-rsc] (ecmascript)");
;
const DashboardContent = (0, __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$server$2d$dom$2d$turbopack$2d$server$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["registerClientReference"])(function() {
    throw new Error("Attempted to call DashboardContent() from the server but DashboardContent is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.");
}, "[project]/Documents/nakis/src/app/(en)/(dashboard)/dashboard/dashboard-content.tsx", "DashboardContent");
}),
"[project]/Documents/nakis/src/app/(en)/(dashboard)/dashboard/dashboard-content.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

var __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$src$2f$app$2f28$en$292f28$dashboard$292f$dashboard$2f$dashboard$2d$content$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__$3c$module__evaluation$3e$__ = __turbopack_context__.i("[project]/Documents/nakis/src/app/(en)/(dashboard)/dashboard/dashboard-content.tsx [app-rsc] (client reference proxy) <module evaluation>");
var __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$src$2f$app$2f28$en$292f28$dashboard$292f$dashboard$2f$dashboard$2d$content$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__ = __turbopack_context__.i("[project]/Documents/nakis/src/app/(en)/(dashboard)/dashboard/dashboard-content.tsx [app-rsc] (client reference proxy)");
;
__turbopack_context__.n(__TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$src$2f$app$2f28$en$292f28$dashboard$292f$dashboard$2f$dashboard$2d$content$2e$tsx__$5b$app$2d$rsc$5d$__$28$client__reference__proxy$29$__);
}),
"[project]/Documents/nakis/src/app/(en)/(dashboard)/dashboard/page.tsx [app-rsc] (ecmascript)", ((__turbopack_context__) => {
"use strict";

__turbopack_context__.s([
    "default",
    ()=>DashboardPage
]);
var __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Documents/nakis/node_modules/next/dist/server/route-modules/app-page/vendored/rsc/react-jsx-dev-runtime.js [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$src$2f$lib$2f$auth$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Documents/nakis/src/lib/auth.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Documents/nakis/src/lib/prisma.ts [app-rsc] (ecmascript)");
var __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$src$2f$app$2f28$en$292f28$dashboard$292f$dashboard$2f$dashboard$2d$content$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__ = __turbopack_context__.i("[project]/Documents/nakis/src/app/(en)/(dashboard)/dashboard/dashboard-content.tsx [app-rsc] (ecmascript)");
;
;
;
;
async function getOrderStats(userId, isAdmin) {
    const where = isAdmin ? {} : {
        customerId: userId
    };
    const pendingStatuses = [
        "ORDERED",
        "PRICED",
        "APPROVAL_AWAITING",
        "REVISION",
        "PAYMENT_PENDING"
    ];
    const [total, pending, inProgress, completed] = await Promise.all([
        __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"].order.count({
            where
        }),
        __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"].order.count({
            where: {
                ...where,
                status: {
                    in: pendingStatuses
                }
            }
        }),
        __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"].order.count({
            where: {
                ...where,
                status: "IN_PROGRESS"
            }
        }),
        __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"].order.count({
            where: {
                ...where,
                status: "COMPLETED"
            }
        })
    ]);
    return {
        total,
        pending,
        inProgress,
        completed
    };
}
async function getRecentOrders(userId, isAdmin) {
    const where = isAdmin ? {} : {
        customerId: userId
    };
    return __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$src$2f$lib$2f$prisma$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["default"].order.findMany({
        where,
        include: {
            customer: {
                select: {
                    name: true,
                    email: true,
                    image: true
                }
            }
        },
        orderBy: {
            createdAt: "desc"
        },
        take: 5
    });
}
async function DashboardPage() {
    const session = await (0, __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$src$2f$lib$2f$auth$2e$ts__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["auth"])();
    const isAdmin = session?.user?.role === "ADMIN";
    const userId = session?.user?.id;
    const stats = await getOrderStats(userId, isAdmin);
    const recentOrders = await getRecentOrders(userId, isAdmin);
    return /*#__PURE__*/ (0, __TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2d$jsx$2d$dev$2d$runtime$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["jsxDEV"])(__TURBOPACK__imported__module__$5b$project$5d2f$Documents$2f$nakis$2f$src$2f$app$2f28$en$292f28$dashboard$292f$dashboard$2f$dashboard$2d$content$2e$tsx__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__["DashboardContent"], {
        stats: stats,
        recentOrders: recentOrders,
        isAdmin: isAdmin
    }, void 0, false, {
        fileName: "[project]/Documents/nakis/src/app/(en)/(dashboard)/dashboard/page.tsx",
        lineNumber: 43,
        columnNumber: 9
    }, this);
}
}),
"[project]/Documents/nakis/src/app/(en)/(dashboard)/dashboard/page.tsx [app-rsc] (ecmascript, Next.js Server Component)", ((__turbopack_context__) => {

__turbopack_context__.n(__turbopack_context__.i("[project]/Documents/nakis/src/app/(en)/(dashboard)/dashboard/page.tsx [app-rsc] (ecmascript)"));
}),
];

//# sourceMappingURL=%5Broot-of-the-server%5D__65b6719b._.js.map