// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(en)/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/(dashboard)/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/(dashboard)/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/(dashboard)/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/(dashboard)/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/(dashboard)/orders/[id]/payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[id]/payment">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/(dashboard)/orders/[id]/payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/(dashboard)/orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/new">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/(dashboard)/orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/(dashboard)/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/(dashboard)/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/(dashboard)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/(dashboard)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/cookie-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cookie-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/cookie-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/delivery-and-returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery-and-returns">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/delivery-and-returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/distance-sales-agreement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/distance-sales-agreement">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/distance-sales-agreement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/faqs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faqs">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/faqs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/(auth)/giris/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/giris">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/(auth)/giris/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/(auth)/kayit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/kayit">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/(auth)/kayit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/(auth)/sifre-sifirla/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/sifre-sifirla">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/(auth)/sifre-sifirla/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/(auth)/sifremi-unuttum/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/sifremi-unuttum">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/(auth)/sifremi-unuttum/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/(dashboard)/ayarlar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/ayarlar">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/(dashboard)/ayarlar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/(dashboard)/musteriler/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/musteriler">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/(dashboard)/musteriler/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/(dashboard)/panel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/panel">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/(dashboard)/panel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/(dashboard)/raporlar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/raporlar">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/(dashboard)/raporlar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/(dashboard)/siparisler/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/siparisler/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/(dashboard)/siparisler/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/(dashboard)/siparisler/[id]/payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/siparisler/[id]/payment">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/(dashboard)/siparisler/[id]/payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/(dashboard)/siparisler/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/siparisler/new">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/(dashboard)/siparisler/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/(dashboard)/siparisler/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/siparisler">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/(dashboard)/siparisler/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/cerez-politikasi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/cerez-politikasi">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/cerez-politikasi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/fiyatlandirma/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/fiyatlandirma">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/fiyatlandirma/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/gizlilik-politikasi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/gizlilik-politikasi">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/gizlilik-politikasi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/hakkimizda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/hakkimizda">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/hakkimizda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/hizmetler/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/hizmetler">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/hizmetler/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/iletisim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/iletisim">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/iletisim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/mesafeli-satis-sozlesmesi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/mesafeli-satis-sozlesmesi">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/mesafeli-satis-sozlesmesi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/sss/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/sss">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/sss/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/teslimat-ve-iade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tr/teslimat-ve-iade">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/teslimat-ve-iade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/users/[id]/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]/notes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/users/[id]/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/logout-all/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout-all">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/logout-all/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comments">> = Specific
  const handler = {} as typeof import("../../../src/app/api/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/cleanup-orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/cleanup-orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/cleanup-orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/files/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/files/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/files/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/files/upload">> = Specific
  const handler = {} as typeof import("../../../src/app/api/files/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/[id]/download-finals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/download-finals">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/[id]/download-finals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/[id]/wilcom/image/[type]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/wilcom/image/[type]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/[id]/wilcom/image/[type]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/[id]/wilcom/pdf/[type]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/wilcom/pdf/[type]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/[id]/wilcom/pdf/[type]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/[id]/wilcom/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/wilcom/publish">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/[id]/wilcom/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/[id]/wilcom/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/[id]/wilcom">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/[id]/wilcom/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders">> = Specific
  const handler = {} as typeof import("../../../src/app/api/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/user/avatar/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/avatar/upload">> = Specific
  const handler = {} as typeof import("../../../src/app/api/user/avatar/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/user/delete-account/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/delete-account/confirm">> = Specific
  const handler = {} as typeof import("../../../src/app/api/user/delete-account/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/user/delete-account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/delete-account">> = Specific
  const handler = {} as typeof import("../../../src/app/api/user/delete-account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/user/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/password">> = Specific
  const handler = {} as typeof import("../../../src/app/api/user/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/user/profile/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile/verify">> = Specific
  const handler = {} as typeof import("../../../src/app/api/user/profile/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/(en)/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(en)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/(en)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tr">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tr">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tr/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tr">> = Specific
  const handler = {} as typeof import("../../../src/app/tr/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
