var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/user/profile/route.js")
R.c("server/chunks/5fc01_next_458f0386._.js")
R.c("server/chunks/5fc01_@auth_core_d5607398._.js")
R.c("server/chunks/5fc01_jose_dist_webapi_ac806f1d._.js")
R.c("server/chunks/5fc01_zod_v4_47c06c22._.js")
R.c("server/chunks/5fc01_59ff8f57._.js")
R.c("server/chunks/[root-of-the-server]__004b382f._.js")
R.c("server/chunks/80b94_nakis__next-internal_server_app_api_user_profile_route_actions_b07c5088.js")
R.m("[project]/Documents/nakis/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/Documents/nakis/src/app/api/user/profile/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/Documents/nakis/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/Documents/nakis/src/app/api/user/profile/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
